FROM webdevops/php-nginx:7.4-alpine


ENV WEB_DOCUMENT_ROOT /app/public
ENV WEB_ALIAS_DOMAIN groovybot.test

WORKDIR /app

COPY . .

RUN composer install -d /app --no-interaction --optimize-autoloader --no-dev


RUN chown -R application:application .
