FROM composer:latest as vendor

WORKDIR /app

COPY database/ database/
COPY tests tests
COPY composer.json composer.json
COPY composer.lock composer.lock

RUN composer update 

RUN composer install

COPY . .
RUN composer dump-autoload


FROM php:7.4-fpm

WORKDIR /app


RUN apt-get update -y && apt-get install -y libmcrypt-dev libzip-dev libpng-dev \
    && docker-php-ext-install pdo_mysql

COPY --from=vendor /app/ /app/


RUN chown -R www-data:www-data /app/
USER www-data

