apiVersion: v1
kind: Service
metadata:
  name: groovy-app
spec:
  selector:
    app: grovybot-deployment
  type: NodePort
  ports: 
    - protocol: TCP
      port: 80
      targetPort: 80


# run this command to get LoadBalancer in minukube : minikube service service name